version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres_altenshop
    environment:
      POSTGRES_USER: altenshop
      POSTGRES_PASSWORD: altenshop
      POSTGRES_DB: altenshop
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  angular-app:
    container_name: front_altenshop
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "4200:4200"

volumes:
  db_data:
